*KEYWORD
*MAT_ELASTIC
         1  7.85E-09  2.10E+05      0.30     0.0     0.0
*SECTION_SOLID
         1         1         0
*PART
$      PID     SECID       MID     EOSID      HGID      GRAV    ADPOPT      TMID
         1         1         1         0         0         0         0         0
*DEFINE_CURVE
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP
         1         0       1.0      -2.0       0.0       0.0         0
                 0.0                 0.0
                 1.0                 1.0
*CONTROL_TERMINATION
     1.0         0       0.0       0.0       0.0
*END
