#include "parser/DynainWriter.h"
#include <iomanip>
#include <sstream>
#include <ctime>

namespace KooRemapper {

DynainWriter::DynainWriter()
    : largeDeformation_(false)
{}

std::string DynainWriter::getCurrentDateTime()
{
    std::time_t now = std::time(nullptr);
    std::tm* ltm = std::localtime(&now);
    
    std::ostringstream oss;
    oss << std::setfill('0')
        << (1900 + ltm->tm_year) << "-"
        << std::setw(2) << (1 + ltm->tm_mon) << "-"
        << std::setw(2) << ltm->tm_mday << " "
        << std::setw(2) << ltm->tm_hour << ":"
        << std::setw(2) << ltm->tm_min << ":"
        << std::setw(2) << ltm->tm_sec;
    
    return oss.str();
}

void DynainWriter::writeHeader(std::ofstream& file,
                               StrainType strainType,
                               const std::string& refFile,
                               const std::string& defFile)
{
    file << "*KEYWORD\n";
    file << "$\n";
    file << "$ LS-DYNA Initial Stress File (dynain)\n";
    file << "$ Generated by KooRemapper\n";
    file << "$ Date: " << getCurrentDateTime() << "\n";
    file << "$\n";
    
    if (!refFile.empty()) {
        file << "$ Reference mesh: " << refFile << "\n";
    }
    if (!defFile.empty()) {
        file << "$ Deformed mesh: " << defFile << "\n";
    }
    
    file << "$ Strain type: " 
         << (strainType == StrainType::ENGINEERING ? "Engineering" : "Green-Lagrange")
         << "\n";
    file << "$ Large deformation: " << (largeDeformation_ ? "Yes" : "No") << "\n";
    file << "$\n";
}

void DynainWriter::writeStressCard(std::ofstream& file, const ElementResult& result)
{
    if (!result.isValid) return;
    
    // *INITIAL_STRESS_SOLID
    // Card 1: eid, nint, nhisv, large, ics, ncomp
    file << "*INITIAL_STRESS_SOLID\n";
    file << "$#    eid    nint   nhisv   large     ics   ncomp\n";
    file << std::setw(10) << result.elementId
         << std::setw(8) << 1        // nint: number of integration points
         << std::setw(8) << 0        // nhisv: history variables
         << std::setw(8) << (largeDeformation_ ? 1 : 0)  // large
         << std::setw(8) << 0        // ics: coordinate system
         << std::setw(8) << 0        // ncomp: components
         << "\n";
    
    // Card 2: sigxx, sigyy, sigzz, sigxy, sigyz, sigxz
    file << "$#  sigxx     sigyy     sigzz     sigxy     sigyz     sigxz\n";
    file << std::scientific << std::setprecision(3);
    file << std::setw(10) << result.stress.xx
         << std::setw(10) << result.stress.yy
         << std::setw(10) << result.stress.zz
         << std::setw(10) << result.stress.xy
         << std::setw(10) << result.stress.yz
         << std::setw(10) << result.stress.xz
         << "\n";
    
    // Card 3: eps (equivalent plastic strain - 0 for elastic)
    file << "$#    eps\n";
    file << std::setw(10) << 0.0 << "\n";
}

bool DynainWriter::writeFile(
    const std::string& filename,
    const MeshAnalysisResult& results,
    StrainType strainType,
    const std::string& refFile,
    const std::string& defFile)
{
    std::ofstream file(filename);
    if (!file.is_open()) {
        errorMessage_ = "Cannot open file for writing: " + filename;
        return false;
    }
    
    // Write header
    writeHeader(file, strainType, refFile, defFile);
    
    // Write stress cards for each element
    for (const auto& result : results.elementResults) {
        if (result.isValid && results.hasMaterial) {
            writeStressCard(file, result);
        }
    }
    
    // End keyword
    file << "*END\n";
    
    file.close();
    return true;
}

bool DynainWriter::writeStrainCSV(
    const std::string& filename,
    const MeshAnalysisResult& results)
{
    std::ofstream file(filename);
    if (!file.is_open()) {
        errorMessage_ = "Cannot open file for writing: " + filename;
        return false;
    }
    
    // Header
    file << "ElementID,CenterX,CenterY,CenterZ,"
         << "eps_xx,eps_yy,eps_zz,eps_xy,eps_yz,eps_xz,"
         << "vonMisesStrain,maxPrincipalStrain,minPrincipalStrain";
    
    if (results.hasMaterial) {
        file << ",sig_xx,sig_yy,sig_zz,sig_xy,sig_yz,sig_xz,"
             << "vonMisesStress,maxPrincipalStress,minPrincipalStress";
    }
    file << "\n";
    
    // Data rows
    file << std::scientific << std::setprecision(6);
    
    for (const auto& r : results.elementResults) {
        if (!r.isValid) continue;
        
        file << r.elementId << ","
             << r.center.x << "," << r.center.y << "," << r.center.z << ","
             << r.strain.xx << "," << r.strain.yy << "," << r.strain.zz << ","
             << r.strain.xy << "," << r.strain.yz << "," << r.strain.xz << ","
             << r.vonMisesStrain << ","
             << r.maxPrincipalStrain << "," << r.minPrincipalStrain;
        
        if (results.hasMaterial) {
            file << "," << r.stress.xx << "," << r.stress.yy << "," << r.stress.zz << ","
                 << r.stress.xy << "," << r.stress.yz << "," << r.stress.xz << ","
                 << r.vonMisesStress << ","
                 << r.maxPrincipalStress << "," << r.minPrincipalStress;
        }
        file << "\n";
    }
    
    file.close();
    return true;
}

} // namespace KooRemapper

