#include "parser/DynainWriter.h"
#include <iomanip>
#include <sstream>
#include <ctime>

// Knowledge graph (lat.md):
//   @lat: [[modules/parser]]

namespace KooRemapper {

DynainWriter::DynainWriter()
    : largeDeformation_(false)
{}

std::string DynainWriter::getCurrentDateTime()
{
    std::time_t now = std::time(nullptr);
    std::tm* ltm = std::localtime(&now);
    
    std::ostringstream oss;
    oss << std::setfill('0')
        << (1900 + ltm->tm_year) << "-"
        << std::setw(2) << (1 + ltm->tm_mon) << "-"
        << std::setw(2) << ltm->tm_mday << " "
        << std::setw(2) << ltm->tm_hour << ":"
        << std::setw(2) << ltm->tm_min << ":"
        << std::setw(2) << ltm->tm_sec;
    
    return oss.str();
}

bool DynainWriter::writeFile(
    const std::string& filename,
    const MeshAnalysisResult& results,
    StrainType strainType,
    const std::string& refFile,
    const std::string& defFile)
{
    // Build entire content in memory first for fast I/O
    std::ostringstream buffer;
    buffer << std::fixed;

    // Write header
    buffer << "*KEYWORD\n";
    buffer << "$\n";
    buffer << "$ LS-DYNA Initial Stress File (dynain)\n";
    buffer << "$ Generated by KooRemapper\n";
    buffer << "$ Date: " << getCurrentDateTime() << "\n";
    buffer << "$\n";

    if (!refFile.empty()) {
        buffer << "$ Reference mesh: " << refFile << "\n";
    }
    if (!defFile.empty()) {
        buffer << "$ Deformed mesh: " << defFile << "\n";
    }

    buffer << "$ Strain type: "
           << (strainType == StrainType::ENGINEERING ? "Engineering" : "Green-Lagrange")
           << "\n";
    buffer << "$ Large deformation: " << (largeDeformation_ ? "Yes" : "No") << "\n";
    buffer << "$\n";
    buffer << "$ Note: Use this file with the deformed mesh (def_mesh), not the reference mesh.\n";
    buffer << "$ Include this file in your deformed mesh model using *INCLUDE.\n";
    buffer << "$\n";

    // Write *INITIAL_STRESS_SOLID keyword once
    buffer << "*INITIAL_STRESS_SOLID\n";

    // Write stress cards for each element
    bool firstElement = true;
    buffer << std::scientific << std::setprecision(3);

    for (const auto& result : results.elementResults) {
        if (!result.isValid || !results.hasMaterial) continue;

        // Card 1: eid, nint, nhisv, large, ics, ncomp
        if (firstElement) {
            buffer << "$#    eid    nint   nhisv   large     ics   ncomp\n";
        }
        buffer << std::setw(10) << result.elementId
               << std::setw(8) << 1
               << std::setw(8) << 0
               << std::setw(8) << 0
               << std::setw(8) << 0
               << std::setw(8) << 0
               << "\n";

        // Card 2: sigxx, sigyy, sigzz, sigxy, sigyz, sigxz, eps
        if (firstElement) {
            buffer << "$#  sigxx     sigyy     sigzz     sigxy     sigyz     sigxz       eps\n";
            firstElement = false;
        }
        buffer << std::setw(10) << result.stress.xx
               << std::setw(10) << result.stress.yy
               << std::setw(10) << result.stress.zz
               << std::setw(10) << result.stress.xy
               << std::setw(10) << result.stress.yz
               << std::setw(10) << result.stress.xz
               << std::setw(10) << 0.0
               << "\n";
    }

    buffer << "*END\n";

    // Write entire buffer to file at once
    std::ofstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        errorMessage_ = "Cannot open file for writing: " + filename;
        return false;
    }

    file << buffer.str();
    file.close();
    return true;
}

bool DynainWriter::writeStrainCSV(
    const std::string& filename,
    const MeshAnalysisResult& results)
{
    // Build entire content in memory first for fast I/O
    std::ostringstream buffer;

    // Header
    buffer << "ElementID,CenterX,CenterY,CenterZ,"
           << "eps_xx,eps_yy,eps_zz,eps_xy,eps_yz,eps_xz,"
           << "vonMisesStrain,maxPrincipalStrain,minPrincipalStrain";

    if (results.hasMaterial) {
        buffer << ",sig_xx,sig_yy,sig_zz,sig_xy,sig_yz,sig_xz,"
               << "vonMisesStress,maxPrincipalStress,minPrincipalStress";
    }
    buffer << "\n";

    // Data rows
    buffer << std::scientific << std::setprecision(6);

    for (const auto& r : results.elementResults) {
        if (!r.isValid) continue;

        buffer << r.elementId << ","
               << r.center.x << "," << r.center.y << "," << r.center.z << ","
               << r.strain.xx << "," << r.strain.yy << "," << r.strain.zz << ","
               << r.strain.xy << "," << r.strain.yz << "," << r.strain.xz << ","
               << r.vonMisesStrain << ","
               << r.maxPrincipalStrain << "," << r.minPrincipalStrain;

        if (results.hasMaterial) {
            buffer << "," << r.stress.xx << "," << r.stress.yy << "," << r.stress.zz << ","
                   << r.stress.xy << "," << r.stress.yz << "," << r.stress.xz << ","
                   << r.vonMisesStress << ","
                   << r.maxPrincipalStress << "," << r.minPrincipalStress;
        }
        buffer << "\n";
    }

    // Write entire buffer to file at once
    std::ofstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        errorMessage_ = "Cannot open file for writing: " + filename;
        return false;
    }

    file << buffer.str();
    file.close();
    return true;
}

} // namespace KooRemapper

