# material_db.json의 모든 재료를 *MAT 키워드 카드로 모아 단일 .k로 출력한다.
"""Export every material in material_db.json as *MAT keyword cards into one .k.

Each DB entry stores a ready-made card string under cards_structural[<mat_type>]
(the material's primary card, with its MID baked into field 1) and a standalone
card_thermal (*MAT_THERMAL_ISOTROPIC). We emit the primary structural card for
all materials, optionally followed by the thermal cards.

Usage:
    python export_all_materials.py [--thermal] [-o all_materials.k]

*MAT_ADD_THERMAL_EXPANSION is intentionally skipped: its PID field is a model-
specific placeholder (library convention), so it is meaningless without a model.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def _clean(card: str) -> str:
    # Drop the trailing "$$ --- MID N: ..." separator comment that leaks the next entry.
    i = card.find("\n$$ ---")
    if i != -1:
        card = card[:i]
    return card.rstrip()


# Card preference (best → worst): prefer the most representative *inelastic* model
# a material actually provides; fall back to elastic only when nothing better
# exists. MAT_RIGID and the MAT_ELASTIC_* approximations of viscoelastic are never
# auto-picked.
_PRIORITY = [
    "MAT_PIECEWISE_LINEAR_PLASTICITY",
    "MAT_PLASTIC_KINEMATIC",
    "MAT_VISCOELASTIC",
    "MAT_GENERAL_VISCOELASTIC",
    "MAT_HYPERELASTIC_RUBBER",
    "MAT_MOONEY-RIVLIN_RUBBER",
    "MAT_SAMP-1",
    "MAT_ORTHOTROPIC_ELASTIC",
    "MAT_ELASTIC",
]


def _pick(m: dict, native_only: bool):
    """Return (card_text, mat_type) for a material, or (None, None)."""
    cards = m.get("cards_structural") or {}
    if not cards:
        return None, None
    if native_only:
        mt = m.get("mat_type")
        return (cards.get(mt) or next(iter(cards.values()))), mt
    for mt in _PRIORITY:
        if mt in cards:
            return cards[mt], mt
    # nothing in the priority list: take any real card (skip rigid + elastic approx)
    for k, v in cards.items():
        if k != "MAT_RIGID" and not k.startswith("MAT_ELASTIC_"):
            return v, k
    mt = m.get("mat_type")
    return (cards.get(mt) or next(iter(cards.values()))), mt


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(HERE / "material_db.json"))
    ap.add_argument("-o", "--output", default=str(HERE / "all_materials.k"))
    ap.add_argument("--thermal", action="store_true", help="also emit *MAT_THERMAL_ISOTROPIC cards")
    ap.add_argument("--native", action="store_true",
                    help="emit each material's native mat_type instead of preferring plastic/viscoelastic")
    ns = ap.parse_args()

    mats = json.load(open(ns.db, encoding="utf-8"))["materials"]
    order = sorted(mats, key=lambda x: int(x))

    mode = "native mat_type" if ns.native else "prefer plastic/viscoelastic over elastic"
    out = ["*KEYWORD",
           f"$ KooRemapper material library — {len(order)} materials from material_db.json",
           f"$ Generated by export_all_materials.py (structural *MAT cards; MID = DB id; {mode})",
           "$ ============================================================"]

    emitted = skipped = 0
    counts: dict[str, int] = {}
    for mid in order:
        card, mt = _pick(mats[mid], ns.native)
        if not card:
            skipped += 1
            continue
        out.append(_clean(card))
        counts[mt] = counts.get(mt, 0) + 1
        emitted += 1

    if ns.thermal:
        out.append("$ ============================================================")
        out.append("$ Thermal material cards (*MAT_THERMAL_ISOTROPIC, TMID = DB id)")
        out.append("$ ============================================================")
        for mid in order:
            ct = mats[mid].get("card_thermal")
            if ct:
                out.append(_clean(ct))

    out.append("*END")
    Path(ns.output).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {ns.output}: {emitted} materials ({skipped} skipped, no card)"
          + (", + thermal" if ns.thermal else ""))
    for mt, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"  {n:4d}  {mt}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
